version: 2
resource: "../temp/resources/"
elements:
  - id: 1-logo
    type: image
    x: 17
    y: 12
    width: 300
    height: 80
    scale:
      - 0.12
      - 0.12
  - id: 2-text
    type: text
    x: 17
    y: 27
    width: 100
    height: 25
    text: ใบนำฝากชำระเงิน (Bill Payment Pay-In Slip)
    fontSize: 14
    fontFamily: 1
    textAlign: left
    verticalAlign: top
  - id: 3-text
    type: text
    x: 17
    y: 32
    width: 100
    height: 5
    text: |-
      บริษัท กสิกร โกลบอล เพย์เมนต์ จำกัด
      ที่อยู่ 87/1 อาคารแคปปิตอลทาวเวอร์ ออลซีซั่นส์เพลส
      ชั้นที่ 10 ห้องเลขที่ S10029 ถนนวิทยุ แขวงลุมพินี
      เขตปทุมวัน กรุงเทพมหานคร 10330
      เลขประจำตัวผู้เสียภาษี {{tax_id}}
    fontSize: 14
    fontFamily: 2
    textAlign: left
    verticalAlign: top
  - id: 4-text
    type: text
    x: 50
    y: 12
    width: 147
    height: 5
    text: |-
      Payment ID: {{payment_id}}
      Order Number: {{order_number}}
    fontSize: 14
    fontFamily: 2
    textAlign: right
    verticalAlign: top
  - id: 5-text
    type: text
    x: 147
    y: 27
    width: 140
    height: 5
    text: สําหรับธนาคาร
    fontSize: 14
    fontFamily: 1
    textAlign: left
    verticalAlign: top
  - id: 6-text
    type: text
    x: 122
    y: 32
    width: 140
    height: 5
    text: |-
      สาขาผู้ฝาก/Branch.............................................
      วันที่/Date.........................................................
      ชื่อลูกค้า (Name)   
      รหัสลูกค้า (Ref.1)  
      รหัสลูกค้า (Ref.2)  
      Tel.
    fontSize: 14
    fontFamily: 1
    textAlign: left
    verticalAlign: top
  - id: 7-text
    type: text
    x: 132
    y: 42
    width: 140
    height: 5
    text:
      "                 {{name}}\n                 {{ref1}}\n                  {{ref2}}\n     {{phone}}"
    fontSize: 14
    fontFamily: 2
    textAlign: left
    verticalAlign: top
  - id: 8-text
    type: text
    x: 17
    y: 71
    width: 140
    height: 5
    text: "เพื่อเข้าบัญชี บริษัท กสิกร โกลบอล เพย์เมนต์ จำกัด\n             บมจ. ธนาคารกสิกรไทย เลขที่บัญชี ${XXX-X-6304X-X} (Com Code {{comp_code}})"
    fontSize: 14
    fontFamily: 1
    textAlign: left
    verticalAlign: top
  - id: 9-ellipse
    type: ellipse
    x: 19
    y: 77
    width: 4
    height: 4
    angle: 0
    strokeWidth: 2
  - id: 10-logo
    type: image
    x: 25
    y: 76
    width: 55
    height: 55
    scale:
      - 0.1
      - 0.
  - id: 11-table
    type: table
    x: 19
    y: 83
    width: 180
    height: 30
  - id: 12-ellipse
    type: ellipse
    x: 20
    y: 89
    width: 2.3
    height: 2.3
    angle: 0
    strokeWidth: 2
  - id: 13-ellipse
    type: ellipse
    x: 33
    y: 89
    width: 2.3
    height: 2.3
    angle: 0
    strokeWidth: 2
  - id: 14-code128
    type: code128
    x: 110
    y: 117
    width: 89
    height: 10
    text: "|{{tax_id}}{{invoice_suffix}}\n{{ref1}}\n{{ref2}}\n{{total_price}}"
  - id: 15-text
    type: text
    x: 118
    y: 127
    width: 140
    height: 5
    text: "| {{tax_id}}{{invoice_suffix}} {{ref1}} {{ref2}} {{total_price}}"
    fontSize: 9
    fontFamily: 2
    textAlign: left
    verticalAlign: top
  - id: 16-text
    type: text
    x: 40
    y: 134
    width: 200
    height: 5
    text: "เพื่อความสะดวกของท่าน กรุณานำใบแจ้งการชำระเงินพร้อมใบแจ้งหนี้ไปชำระได้ที่ ธ.กสิกรไทย ทุกสาขาทั่วประเทศ"
    fontSize: 13
    fontFamily: 1
    textAlign: left
    verticalAlign: top
  - id: 17-line
    type: line
    x: 18
    y: 143
    strokeWidth: 2
    points:
      - - 0
        - 0
      - - 180
        - 0
  - id: 18-copy
    type: copy
    x: 0
    y: 135
appState:
  gridSize:
  viewBackgroundColor: "#ffffff"
tables:
  11-table:
    columnRatio:
      - 0.14
      - 0.125
      - 0.125
      - 0.2
      - 0.175
      - 0.235
    rowRatio:
      - 0.18
      - 0.18
      - 0.18
      - 0.46
    mergeCell:
      A4: D4
      E4: F4
    hiddenEdge:
      A4: LB
    cellText:
      A1:
        text: รายการ
        fontFamily: 1
        fontSize: 14
      B1:
        text: ธนาคาร/Bank
        fontFamily: 1
        fontSize: 14
      C1:
        text: สาขา/Branch
        fontFamily: 1
        fontSize: 14
      D1:
        text: เลขที่เช็ค/Cheque No.
        fontFamily: 1
        fontSize: 14
      E1:
        text: เช็คลงวันที่/Date
        fontFamily: 1
        fontSize: 14
      F1:
        text: จำนวนเงิน(บาท)/Amount
        fontFamily: 1
        fontSize: 14
      A2:
        text:  เงินสด    เช็ค
        fontFamily: 1
        fontSize: 14
      F2:
        text: "{{total_price_str}}"
        fontFamily: 1
        fontSize: 14
      A4:
        text: "ชื่อผู้นำฝาก/Deposit by........................................ โทร./Tel........................"
        fontFamily: 1
        fontSize: 14
        verticalAlign: bottom
      E4:
        text: "สำหรับเจ้าหน้าที่ธนาคาร\nผู้รับเงิน............................................................"
        fontFamily: 1
        fontSize: 14
files:
  1-logo:
    mimeType: image/png
    id: pic1
    dataURL: coral_logo_black.png
    created: 1702548227802
    lastRetrieved: 1702548227802
  10-logo:
    mimeType: image/png
    id: pic2
    dataURL: kbank_logo.png
    created: 1702548227802
    lastRetrieved: 1702548227802
  kbank-logo1:
    mimeType: image/png
    id: pic1
    dataURL: kbank_logo.png
    created: 1702548227802
    lastRetrieved: 1702548227802
fonts:
  - familyName: sarabun
    style: B
    dataURL: sarabun_bold.ttf
  - familyName: sarabun
    style: ""
    dataURL: sarabun_regular.ttf
copies:
  18-copy:
    - 1-logo
    - 2-text
    - 3-text
    - 4-text
    - 5-text
    - 6-text
    - 7-text
    - 8-text
    - 9-ellipse
    - 10-logo
    - 11-table
    - 12-ellipse
    - 13-ellipse
    - 14-code128
    - 15-text
    - 16-text
paper:
  size: A4
  unit: mm
  orientation: P